service: school-console-api

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-optimize

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!**'
    - 'dist/apps/api/**'

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    TZ: ${env:TZ}
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    COOKIE_SECRET: ${env:COOKIE_SECRET}
    CORS_ORIGINS: https://school-console.subhojitghosh.com

functions:
  main:
    handler: dist/apps/api/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
