service: school-console-api

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-optimize

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!**'
    - 'dist/apps/api/**'

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  main:
    handler: dist/apps/api/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
